services:
  kas-ddns-updater:
    image: ghcr.io/iljabecker/kas-ddns-updater:latest
    container_name: kas-ddns-updater
    ports:
      - "8001:8000"
    restart: unless-stopped
    environment:
      - KAS_LOGIN=${KAS_LOGIN}
      - KAS_PASSWORD=${KAS_PASSWORD}
      - TZ=Europe/Berlin
    volumes:
      - kas-ddns-data:/data

volumes:
  kas-ddns-data:
